language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

os:
  - linux
  # - osx

install:
  - pip install -r requirements.txt


script:
  - pytest


jobs:
  include:
    - stage: deploydocs
      python: "3.8"
      install: pip install -r requirements.txt sphinx sphinx-rtd-theme sphinx-automodapi
      script: (cd docs && make html)
      deploy:
        provider: pages:git
        github_token: $GITHUB_TOKEN
        verbose: true
        edge: true
        local-dir: docs/build/html
        on:
          branch: master
