language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

os:
  - linux
  # - osx

install:
  - pip install -r requirements.txt

script:
  - pytest

before_deploy:
  - pip install Sphinx sphinx-rtd-theme sphinx-automodapi

deploy:
  - (cd docs/ && make html)
  provider: pages:git
  verbose: true
  token: $GITHUB_TOKEN
  cleanup: false
  skip_cleanup: true
  on:
    branch: master
  edge: true