language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

os:
  - linux
  # - osx

install:
  - pip install -r requirements.txt
  - pip install --user travis-sphinx


script:
  - pytest
  - travis-sphinx build


# before_deploy:
#   - pip install Sphinx sphinx-rtd-theme sphinx-automodapi
#   - (cd docs/ && make html)

# deploy:
#   on:
#     branch: master
#   cleanup: false
#   verbose: true
#   provider: pages:git
#   token: $GITHUB_TOKEN
#   edge: true


after_success:
  - travis-sphinx deploy
